name: Has hsds_schema.py been run
on: [push, pull_request]

jobs:
  has_hsds_schema_py_been_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        architecture: x64
    - run: sudo apt-get install graphviz libgraphviz-dev pkg-config
    - run: pip install -r requirements.txt
    - run: hsds_schema.py docs-all
    - run: git diff --exit-code
