name: Has hsds_schema.py been run
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - run: sudo apt-get install graphviz libgraphviz-dev pkg-config
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - run: pip install -r requirements.txt
    - run: hsds_schema.py docs-all
    - run: git diff --exit-code
