name: Test Examples (datapackage)
on: [push, pull_request]

jobs:
  test_examples_datapackage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        architecture: x64
    - name: Install Python libs
      run: pip install --upgrade frictionless
    - name: Validate example
      run: frictionless validate examples/csv/datapackage.json
