name: Mysql
on: [push, pull_request]

jobs:
  mysql:
    runs-on: ubuntu-20.04
    services:
      mysql:
        # 8 is chosen because that matches the version of the client utils we will install
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 1234
        ports:
          - 3306:3306/tcp
        options: >-
          --health-cmd "/usr/bin/mysql -h 127.0.0.1 --user=root --password=1234 --execute \"SHOW DATABASES;\""
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - name: Install Ubuntu libs
      run: sudo apt-get install -y graphviz graphviz-dev
    - name: Install Python libs
      run: pip install -r requirements.txt
    - name: Install Python Dev libs
      run: pip install -r requirements_dev.in
    - run: sudo apt-get -y install mysql-client-8.0
    - run: GITHUB_ACTIONS=1 ./build_database_mysql.sh
    - run: diff database/database_mysql.sql database/compare.sql
