name: Test Examples (JSON Schema)
on: [push, pull_request]

jobs:
  test_examples_json_schema:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        architecture: x64
    - run: sudo apt-get install python3-dev graphviz libgraphviz-dev pkg-config
    - run: pip install -r requirements.txt
    - run: ./validate_examples_json_schema.sh
